project:
  type: website
  output-dir: docs

website:
  title: "Katelyn K Nguyen's Portfolio"
  navbar:
    left:
      - href: index.qmd
        # text: Home
      - href: projects.qmd
        text: Projects
      - href: math-437.qmd
        text: Math 437 Final Project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: "darkblue"
    mainfont: "sarif"

editor: visual

